[build]
  publish = "frontend/dist"
  command = "npm run build:frontend"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production]
  command = "cd frontend && npm ci && npm run build"

[context.deploy-preview]
  command = "cd frontend && npm ci && npm run build"

[context.branch-deploy]
  command = "cd frontend && npm ci && npm run build"